services:
  apache:
    image: httpd:2.4
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./vite/dist:/usr/local/apache2/htdocs
    ports:
      - "80:80"
